### PR TITLE
fix: detect near_bindgen-generated functions on rustc >= 1.87

### PR DESCRIPTION
**Pull request by r-near**
Since rustc 1.87, `#[cfg]` attributes are evaluated and stripped before attribute proc macros run, so `is_near_bindgen_wrapped_or_marshall` no longer sees the `#[cfg(target_arch = "wasm32")]` marker on near-sdk-generated wrapper functions. The plugin macros (`only`, `pause`, `if_paused`, `access_control_any`, ...) then re-expand on the self-less `extern "C"` wrappers and inject `self.*` guard code into them, failing with `error[E0424]: expected value, found module 'self'`. This affects any rustc >= 1.87 with any near-sdk version; it surfaced now because contract builds were previously capped at rustc 1.86.

Fix: detect generated wrappers by their shape — `extern "C"` + `#[no_mangle]` (or `#[unsafe(no_mangle)]`) — which user-written functions never have, keeping receiverless user entry points (e.g. `#[init(ignore_state)]` migrations annotated with `#[only(self)]`) processed as before. The old cfg-token heuristic stays as a fallback for older rustc.

Repro:

```rust
#[near]
impl Counter {
    #[only(owner)]
    pub fn protected(&mut self) { self.counter += 1; }
}
```

```
cargo +1.93.0 build --target wasm32-unknown-unknown --release
# error[E0424]: expected value, found module `self`  (compiles fine on <= 1.86)
```

### CODE REVIEW

File: near-plugins-derive/src/utils.rs [hunk 1]
```diff
@@ -8,6 +8,14 @@ use syn::{Ident, ItemFn, Meta};
...
 /// [generated by near_bindgen]: https://github.com/near/near-sdk-rs/issues/722
 pub(crate) fn is_near_bindgen_wrapped_or_marshall(item: &ItemFn) -> bool {
+    // Since rustc 1.87, `#[cfg]` attributes are evaluated and stripped before attribute
+    // proc macros run, so the cfg-based heuristic below no longer sees near_bindgen's
+    // `#[cfg(target_arch = "wasm32")]` marker on generated wrapper functions. The generated
+    // wrapper/marshall functions never take `self`, while plugin macros are only meaningful
+    // on methods, so treat any function without a `self` receiver as generated.
+    if item.sig.receiver().is_none() {
+        return true;
+    }
```
[the remark this answers is not in the document]
Comment (r-near) [reply near-plugins-derive/src/utils.rs]: Good catch — `only(self)` injects `assert_self()`, which doesn't reference the `self` keyword, so receiverless entry points are legitimate targets. Addressed in c4691fd: detection now matches the generated wrapper's shape (`extern "C"` + `no_mangle`/`unsafe(no_mangle)`) instead of the missing receiver. Verified via macro expansion that a receiverless `#[only(self)]` method keeps its injected `assert_self()` while the generated wrapper is still skipped.

[the remark this answers is not in the document]
Comment (r-near) [reply near-plugins-derive/src/utils.rs]: Agreed — same conclusion as the comment above. c4691fd switches to wrapper-shape detection (`extern "C"` + `no_mangle`, both attribute spellings), so user-annotated associated functions are processed normally again. The rustdoc on the helper is also updated to match the actual heuristic.
